### ISSUE TITLE
unable to enumerate USB device

### ISSUE THREAD

**Issue by tobiasgiese** [stecman/hw-boot-selection#10]
I bought a fresh STM32F103 (blue pill), as I initially bought a CKS32F103.

The problem now is, that the device will not be recognized as a USB device.

```
Aug 17 11:39:07 tobias-linux kernel: usb 1-4: new full-speed USB device number 115 using xhci_hcd
Aug 17 11:39:07 tobias-linux kernel: usb 1-4: Device not responding to setup address.
Aug 17 11:39:07 tobias-linux kernel: usb 1-4: Device not responding to setup address.
Aug 17 11:39:08 tobias-linux kernel: usb 1-4: device not accepting address 115, error -71
Aug 17 11:39:08 tobias-linux kernel: usb usb1-port4: unable to enumerate USB device
```

If I plug in my clone stm32, I will get the following

```
Aug 17 11:39:54 tobias-linux kernel: usb 1-4: new full-speed USB device number 116 using xhci_hcd
Aug 17 11:39:54 tobias-linux kernel: usb 1-4: device descriptor read/64, error -71
Aug 17 11:39:54 tobias-linux kernel: usb 1-4: New USB device found, idVendor=26ba, idProduct=8003, bcdDevice= 2.00
Aug 17 11:39:54 tobias-linux kernel: usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Aug 17 11:39:54 tobias-linux kernel: usb 1-4: Product: Boot Switch
Aug 17 11:39:54 tobias-linux kernel: usb 1-4: Manufacturer: Stecman
Aug 17 11:39:54 tobias-linux kernel: usb 1-4: SerialNumber: D000000000E7
Aug 17 11:39:54 tobias-linux kernel: usb-storage 1-4:1.0: USB Mass Storage device detected
Aug 17 11:39:54 tobias-linux kernel: scsi host7: usb-storage 1-4:1.0
```

But flashing was successful of the new real STM32.

```
$ make flash PROGRAMMER=stlink
  LD	boot-swtich.stm32f103c8.elf
  OBJCOPY	boot-swtich.stm32f103c8.bin

Firmware size (boot-swtich.stm32f103c8.elf):

   text	   data	    bss	    dec	    hex	filename
   8128	    112	   1020	   9260	   242c	boot-swtich.stm32f103c8.elf

Flash: 12% (8240 / 65536 bytes)
RAM: 5% (1132 / 20480 bytes)

BINARY=boot-swtich.stm32f103c8.elf openocd -f interface/stlink.cfg -c "transport select hla_swd" -f target/stm32f1x.cfg -f openocd.cfg -c 'program_and_run ()'
Open On-Chip Debugger 0.11.0-rc2
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
attach
Info : clock speed 1000 kHz
Info : STLINK V2J17S4 (API v2) VID:PID 0483:3748
Info : Target voltage: 3.205253
Info : stm32f1x.cpu: hardware has 6 breakpoints, 4 watchpoints
Info : starting gdb server for stm32f1x.cpu on 3333
Info : Listening on port 3333 for gdb connections
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x080016a8 msp: 0x20005000
Info : device id = 0x10006412
Info : flash size = 32kbytes
shutdown command invoked
```

Do you have any idea? Unfortunately I'm no hardware programmer.
I'm thankful for any help :)

**Comment by stecman** [comment]
What's the frequency of the crystal on your new board? The code in `clock.c` is set up for an 8MHz crystal, but 12MHz is also common. There'll be a number etched or printed on the crystal something like this:

![STM32 Blue Pill Crystal 8.000MHz](https://user-images.githubusercontent.com/2230769/129705422-e59fe171-ef0d-4294-bff1-5885a7be6b34.jpg)

For a 12MHz crystal, you should only need to change the argument on [line 86 in `clock.c`](https://github.com/stecman/hw-boot-selection/blob/7e06fedcb1ce3ea3a1c202d07ebb05de02d70c83/src/clock.c#L86) to `RCC_CFGR_PLLMUL_PLL_CLK_MUL4`. The USB peripheral needs a clock of 48MHz (4 x 12 = 48), but it'll be getting 72MHz if this is the case (6 x 12 = 72).

**Comment by tobiasgiese** [comment]
It's also a 8MHz crystal 😿 

![IMG_5203](https://user-images.githubusercontent.com/23076619/129707667-de8c46ca-8bec-43e6-9980-dcdacdd6e6cd.JPG)

**Comment by tobiasgiese** [comment]
Further, I've checked all soldering points for shorts. Nothing suspicious

**Comment by stecman** [comment]
Hmm, a few things to check/try if you haven't already:

- Disconnecting and connecting the controller (it could be stuck in halt)
- Try a different USB cable as a sanity check
- Verify a simple blink program runs (just replace your `main.c` contents with this)

```c
#include "clock.h"

#include <libopencm3/stm32/gpio.h>
#include <libopencm3/stm32/rcc.h>

int main(void)
{
    init_clocks();

    rcc_periph_clock_enable(RCC_GPIOC);
    gpio_set_mode(GPIOC, GPIO_MODE_OUTPUT_2_MHZ, GPIO_CNF_OUTPUT_PUSHPULL, 0xFFFF);

    while (1) {
        gpio_toggle(GPIOC, 0xFFFF);
        for (uint32_t i = 0; i != 0xFFFFF; i++) {}
    }
}
```

- Confirm the part number on the microcontroller chip. My example says STM32F103C8T6, but worth checking what you've got there as I can't quite read it in your photo.
- Connect USB without the programming wires connected
- Try a different USB cable

The "`Device not responding to setup address....device not accepting address 115, error -71`" message comes up even if the controller is held in reset or running firmware that doesn't use the USB peripheral, so it could really be anything, but should be possible to work through by a process of elimination.

**Comment by tobiasgiese** [comment]
Ahh, thanks for that hint.
I have a `stm32f103c6t6` and defining the `DEVICE` env did the trick.

Thanks so much! :)

**Comment by tobiasgiese** [comment]
You could add `stm32f103c6` as tested device to the README.md :) 🥳

**Comment by stecman** [comment]
I've updated this to build against the lowest-spec part in the f103 series, which will work out of the box for any variant :+1:

If you're curious, the issue here will have been the stack pointer getting set to an address past the end of your chip's smaller RAM, probably causing a hard-fault (which is handled by an infinite loop by default).

**Comment by tobiasgiese** [comment]
Ah, that makes total sense. Thank you for the explanation 🙂 

Does it make sense to mention the semi-functional `cks32f103`? This chip will work, but it will not be detected to 100%.
My new blue pill is working perfectly, like [you've described](https://hackaday.io/project/179539-hardware-boot-selection-switch/log/196047-simplified-hardware-boot-switch/discussion-166458).

**Comment by stecman** [comment]
I've added a note to the troubleshooting section about the issues you had with the CKS chip 👍

That part number doesn't work when given to the `DEVICE` build variable, but you're right that it should be mentioned. Thanks!
