### ISSUE TITLE
GRUB 2.06 doesn't recognize filesystem on device.

### ISSUE THREAD

**Issue by bentglasstube** [stecman/hw-boot-selection#11]
Hello,  I have followed the instructions in this github and the hackaday post and while I am in linux I can mount the "drive" and see the FAT filesystem and files.  However, when I drop to a grub shell and attempt to see the files I get this:

    grub> ls (hd0)
    Device hd0: No known filesystem detected - Sector size 512B - Total size 64KiB

I have another drive which is Arch Linux installation media and grub can identify that one as having a FAT partition just fine.  Do you have any suggestions for how to debug this further?

**Comment by stecman** [comment]
Hey, interesting...first time I've seen this. What version of Grub is on each of these systems?

A few things to investigate:

- I presume `search --fs-uuid 55AA-6922` is returning `(hd0)` as the device geometry looks correct, but worth confirming there's nothing else being returned with that command. Odd if it can find the filesystem by UUID but not actually read it.

- If you run `lsmod` in grub, is the `fat` module listed? If not, does running `insmod fat` change the behaviour? If there's too much text for one screen, you can run `set pager=1` before `lsmod`.

- If you plug in a FAT formatted flash drive to the problem machine, are you able to list it in Grub? If you can, that might indicate there's something faulty with the filesystem presented by this firmware.

- To confirm there's not some weird issue with accessing the data on the device, you can run `hexdump -n 1750 (hd0)` in grub which should look something like this:

  ```
  00000000  eb 3c 90 6d 6b 66 73 2e  66 61 74 00 02 01 01 00  |.<.mkfs.fat.....|
  00000010  02 00 02 80 00 f8 01 00  20 00 40 00 00 00 00 00  |........ .@.....|
  00000020  00 00 00 00 00 00 29 22  69 aa 55 53 57 49 54 43  |......)"i.USWITC|
  00000030  48 20 20 20 20 20 46 41  54 31 32 20 20 20 00 00  |H     FAT12   ..|
  00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
  *
  000001f0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 55 aa  |..............U.|
  00000200  f8 ff ff 00 f0 ff ff 0f  00 00 00 00 00 00 00 00  |................|
  00000210  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
  *
  00000400  f8 ff ff 00 f0 ff ff 0f  00 00 00 00 00 00 00 00  |................|
  00000410  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
  *
  00000600  42 6f 00 6e 00 00 00 ff  ff ff ff 0f 00 6f ff ff  |Bo.n.........o..|
  00000610  ff ff ff ff ff ff ff ff  ff ff 00 00 ff ff ff ff  |................|
  00000620  01 73 00 77 00 69 00 74  00 63 00 0f 00 6f 68 00  |.s.w.i.t.c...oh.|
  00000630  5f 00 70 00 6f 00 73 00  69 00 00 00 74 00 69 00  |_.p.o.s.i...t.i.|
  00000640  53 57 49 54 43 48 7e 31  20 20 20 00 00 00 00 00  |SWITCH~1   .....|
  00000650  00 00 00 00 00 00 00 00  00 00 03 00 01 00 00 00  |................|
  00000660  42 6f 00 6e 00 5f 00 67  00 72 00 0f 00 31 75 00  |Bo.n._.g.r...1u.|
  00000670  62 00 2e 00 63 00 66 00  67 00 00 00 00 00 ff ff  |b...c.f.g.......|
  00000680  01 73 00 77 00 69 00 74  00 63 00 0f 00 31 68 00  |.s.w.i.t.c...1h.|
  00000690  5f 00 70 00 6f 00 73 00  69 00 00 00 74 00 69 00  |_.p.o.s.i...t.i.|
  000006a0  53 57 49 54 43 48 7e 31  43 46 47 00 00 00 00 00  |SWITCH~1CFG.....|
  000006b0  00 00 00 00 00 00 00 00  00 00 04 00 13 00 00 00  |................|
  000006c0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
  000006d0  00 00 00 00 00 00                                 |......|
  ```

**Comment by bentglasstube** [comment]
Sorry if I was unclear.  There is only one system involved.  It is running grub v2.06.  The fat module does show up in the output of lsmod, and unsurprisingly there is no change when doing `insmod fat`.

The search command says something like "no such device" and the hexdump output looked correct.  I will attach a photo of the dump output.
![Uploading PXL_20220311_230031720.MP.jpg…]()

**Comment by bentglasstube** [comment]
![PXL_20220311_230031720 MP](https://user-images.githubusercontent.com/449061/157987232-be4222ed-e373-4e3c-83ec-0e6d648c687f.jpg)

**Comment by bentglasstube** [comment]
Some more observations:

The working FAT partitions I have are not FAT12 so that could be the problem.  They appear to all be FAT32.

The working drives also have partitions, but the stm32 device presents itself as a drive that hds no partitions.  Presumably this is fine, as Linux is able to mount it just fine.  It is still a difference between the working and non-working devices though.

**Comment by stecman** [comment]
Thanks - yeah I'm just having a go at running Grub 2.06 in a VM to test this theory, as all of my systems are using 2.04. The 2.04 to 2.06 changelog shows a few FAT modue changes, but nothing saying FAT12 support is removed, so it might have been broken accidentally if it's a version issue.

If you have a spare flash drive, you also test this by formatting it as FAT12 and seeing if Grub can access it:

```sh
sudo mkfs.fat -F 12 -S 512  /dev/someflashdrive 64000
```

**Comment by stecman** [comment]
Ok, so there's definitely something that's changed in 2.06 that's causing this problem. I'll have a look into updating the firmware to fix this.

Grub 2.06 detects a freshly formatted FAT12 filesystem fine, but gets the "No known filesystem detected" message when using a copy of the mock filesystem. Changing back to Grub 2.04 detects the mock filesystem fine.

**Comment by bentglasstube** [comment]
Thanks for the investigation.  I can poke around at it as well and see if I can make any progress, but I haven't worked much at the byte level of filesystems.

**Comment by stecman** [comment]
This turned out to be new code in GRUB 2.06 erroring because the modified date of the presented files was zero. It's a valid check, so I've updated the code to return a hard-coded date.

Thanks for raising this, @bentglasstube :tada:

**Comment by bentglasstube** [comment]
Thanks for the quick fix, GRUB is detecting the file correctly now but my config doesn't seem to be working for some other reason.  Really appreciate this project <3
