### ISSUE TITLE
Add support to build for STM32F103 (common "blue pill" dev board)

### ISSUE THREAD

**Issue by stecman** [stecman/hw-boot-selection#2]
This project is currently set up to build for just the STM32F070, including some specific configuration required for the F6 package of that chip that is unlikely to compile for other STM32 models.

To make this a little more accessible, it would be good to add support for building for the STM32F103, which is far more common on cheap development boards than the chip I've used.

**Comment by alejoberardino** [comment]
Hey @stecman, I just finished setting this up with a blue pill and an st-link programmer, it's working perfectly. I'm a programmer and don't have much experience with microcontrollers, so the support for common hardware has made it simple for me to clone and use this project. It's a fantastic idea and will definitely make my life easier, I just wanted to say thanks!
