### ISSUE TITLE
Is it possible to use on clover (Win 10 / MacOS)?

### ISSUE THREAD

**Issue by vitinhosessa** [stecman/hw-boot-selection#4]
I love the project and i'm very interested, dou you know if this is possible?

**Comment by stecman** [comment]
I'm not familiar with [Clover EFI boot loader](https://github.com/CloverHackyColor/CloverBootloader), but looking at the way it's configured I suspect it will be a bit trickier than it was with GRUB.

I'd suggest asking the developers if it's possible to load additional config from a volume, or look into building Clover with your own modifications to read from the switch.
