### ISSUE TITLE
Q/A 

### ISSUE THREAD

**Issue by jesusvallejo** [stecman/hw-boot-selection#6]
Very happy with the project, not an issue, just i though it would be easier for some people if you add to the readme a couple things.
1. Switch is pull up detected on pin A6, so switch must be connected to A6 pin and GND.(As you published binaries , so they dont have to scroll through the code).
2. Depending on the mobo the usb devices are not detected on grub, change from "fast boot" to "normal boot", `nativedisk` could also be used but it can make your grub not to know how to boot into windows as there is some problem with chainloader.
3. The grub file to edit is, `/boot/grub/grub.cfg`(eventhough it is not recommended), as if you edit `/etc/default/grub`  when you try to `sudo update-grub` it wont work. Also just paste it at the end of the file.(This can seem straight forward, but it isnt for newbies).

**Comment by stecman** [comment]
Thanks @jesusvallejo - all good points. I've updated the readme 👍
