### ISSUE TITLE
Error while flashing

### ISSUE THREAD

**Issue by Matipolit** [stecman/hw-boot-selection#7]
I get this output while executing `make flash PROGRAMMER=stlink` :
```
  LD boot-swtich.stm32f103c8.elf
  OBJCOPY	boot-swtich.stm32f103c8.bin

Firmware size (boot-swtich.stm32f103c8.elf):

   text	   data	    bss	    dec	    hex	filename
   8128	    112	   1020	   9260	   242c	boot-swtich.stm32f103c8.elf

Flash: 12% (8240 / 65536 bytes)
RAM: 5% (1132 / 20480 bytes)

BINARY=boot-swtich.stm32f103c8.elf openocd -f interface/stlink.cfg -c "transport select hla_swd" -f target/stm32f1x.cfg -f openocd.cfg -c 'program_and_run ()'
Open On-Chip Debugger 0.11.0-rc2
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
attach
Info : clock speed 1000 kHz
Info : STLINK V2J29S7 (API v2) VID:PID 0483:3748
Info : Target voltage: 3.232848
Warn : UNEXPECTED idcode: 0x2ba01477
Error: expected 1 of 1: 0x1ba01477
openocd.cfg:16: Error: 
in procedure 'program_and_run' 
in procedure 'program' called at file "openocd.cfg", line 16

make: *** [Makefile:64: flash] Error 1
```

I'm new to st-link programming so any help is appreciated

**Comment by stecman** [comment]
Hi @Matipolit, the key lines here are:

    Warn : UNEXPECTED idcode: 0x2ba01477
    Error: expected 1 of 1: 0x1ba01477

Searching online suggests [you may have a clone chip, not an original STM32](https://community.platformio.org/t/debugging-of-stm32f103-clone-bluepill-board-wrong-idcode/14635). This should still work, but you'll need to add the following to the OpenOCD arguments to the end of `OOCD_FLAGS` in the Makefile to make it program:

    -c set CPUTAPID 0x2ba01477

**Comment by Matipolit** [comment]
> Thanks for the help. Unfortunately, I gen an unexpected argument error:
> `Unexpected command line argument: CPUTAPID`

The command needs to be put in quotation marks, like this:
`-c "set CPUTAPID 0x2ba01477" \`

**Comment by stecman** [comment]
Aha, thanks for figuring that out :+1:

**Comment by veronduh** [comment]
Hi, I am actually also hitting this error. The error persists even after adding -c "set CPUTAPID 0x2ba01477" to OOCD_FLAGS in the Makefile. I can open a new issue if preferred.
Also very new to stm32 programming so any help is appreciated!

**Comment by stecman** [comment]
Hey @veronduh, can you paste the command you're running and all the output?

**Comment by veronduh** [comment]
> Hey @veronduh, can you paste the command you're running and all the output?

Sure thing


user@desktop:~ / hw-boot-selection$ sed -n 50,55p Makefile 
	OOCD_FLAGS = -f interface/$(PROGRAMMER).cfg \
	             -c "transport select $(TRANSPORT)" \
	             -f target/$(OOCD_TARGET).cfg \
	             -f openocd.cfg \
		     -c "set CPUTAPID 0x2ba01477"
endif
user@desktop:~/hw-boot-selection$ make flash PROGRAMMER=stlink
  LD	boot-switch.stm32f103c8.elf
  OBJCOPY	boot-switch.stm32f103c8.bin

Firmware size (boot-switch.stm32f103c8.elf):

   text	   data	    bss	    dec	    hex	filename
   8224	    112	   1020	   9356	   248c	boot-switch.stm32f103c8.elf

Flash: 12% (8336 / 65536 bytes)
RAM: 5% (1132 / 20480 bytes)

BINARY=boot-switch.stm32f103c8.elf openocd -f interface/stlink.cfg -c "transport select hla_swd" -f target/stm32f1x.cfg -f openocd.cfg -c "set CPUTAPID 0x2ba01477" -c 'program_and_run ()'
Open On-Chip Debugger 0.11.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
attach
0x2ba01477
Info : clock speed 1000 kHz
Info : STLINK V2J39S7 (API v2) VID:PID 0483:3748
Info : Target voltage: 3.244800
Warn : UNEXPECTED idcode: 0x2ba01477
Error: expected 1 of 1: 0x1ba01477
openocd.cfg:16: Error: 
in procedure 'program_and_run' 
in procedure 'program' called at file "openocd.cfg", line 16

make: *** [Makefile:74: flash] Error 1
user@desktop:~/hw-boot-selection$

I'll also add I seem to be able to flash fine using cubeprogrammer.
